---
- name: Install nop commerce
  hosts: all
  become: yes
  tasks:
    - name: Install .Net
      get_url:
        url: https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
        dest: /tmp/packages-microsoft-prod.deb
        state: present

    - name: Pass options to dpkg on run
      apt:
        dpkg_options: 'packages-microsoft-prod.deb'
    - name: Install the .NET Core Runtime
      apt: 
        name:
          - install apt-transport-https
          - aspnetcore-runtime-3.1
        update_cache: yes  
        state: present     


    