---
- name: install nop commerce
  become: yes
  hosts: appserver
  tasks:
    - name: download the debian file
      get_url:
        url: https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
        dest: /tmp/packages-microsoft-prod.deb
    - name: install the debian package
      apt:
        deb: /tmp/packages-microsoft-prod.deb
    - name: install .net core runtimes
      apt:
        name: "{{ item }}"
        update_cache: yes
        state: present
      with_items:
       - apt-transport-https 
       - aspnetcore-runtime-3.1
    - name: install nginx
      apt:
        name: nginx 
        update_cache: yes
        state: present 
      notify:
        - start nginx   
  handlers:
    - name: start nginx
      ansible.builtin.systemd:
        name: nginx
        enabled: yes
        state: started 
    - name: configure nginx as a reverse proxy
      ansible.builtin.copy:
        src: serverconfiguration.xml
        dest: /etc/nginx/sites-available/default
    - name: Download foo.confnopCommerce
      get_url:
        url: sudo wget https://github.com/nopSolutions/nopCommerce/releases/download/release-4.40.4/nopCommerce_4.40.4_NoSource_linux_x64.zip
        dest: /tmp/www/nopCommerce440/nopCommerce_4.40.4_NoSource_linux_x64.zip
    - name: Unarchive a file that is already on the remote machine
      ansible.builtin.unarchive:
        src: /tmp/nopCommerce440/nopCommerce_4.40.4_NoSource_linux_x64.zip
        dest: /var/www/nopCommerce440
        remote_src: yes    
    - name: directories to run nopCommerce 
      ansible.builtin.file:
        stat:
        path: "{{ folder }}"
        with_folders:
          - /var/www/nopCommerce440/bin
          - /var/www/nopCommerce440/logs
        state: directory
    - name: Recursively change ownership of a directory
      ansible.builtin.file:
        path: /var/www
        state: directory
        recurse: yes
        owner: nopCommerce440
        group: nopCommerce440  
    - name: configure nopCommerce service
      ansible.builtin.copy:
        src: nopCommerce.service
        dest: /etc/systemd/system/nopCommerce440.service file
    - name: Reload service nopCommerce
      ansible.builtin.systemd:
        name: nopCommerce440.service
        state: started
        enabled: yes
    - name: restart nginx
      ansible.builtin.systemd:
        state: restarted
        daemon_reload: yes
         


    